services:
  broker-service:
    build:
      context: ./../Broker-Service
      dockerfile: ./cmd/api/docker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    