FROM golang:1.21-alpine as builder

WORKDIR /app

COPY . .

RUN go mod tidy

RUN CGO_ENABLED=0 go build -o frontApp ./cmd/web

# Final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/frontApp .
COPY --from=builder /app/cmd/web/templates ./cmd/web/templates

EXPOSE 80

CMD ["./frontApp"] 